### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Zedroid** [tallero/PGPgram#2]
I would like it if you would please port it to windows.  I want to backup and upload my folders automatically to telegram.

**Comment by tallero** [comment]
Almost ready for almost an year (MinGW). I even already compiled the library but I never added the check. Pushing it in a few days.

**Comment by Zedroid** [comment]
Simply wonderful! Great news!

**Comment by Zedroid** [comment]
Any news or updates?

**Comment by tallero** [comment]
I am setting up a windows VM.

**Comment by Zedroid** [comment]
Suh-weet thanks for the update!

**Comment by tallero** [comment]
Released 0.4 with windows support, please test it!
